# Generated by Django 4.0.3 on 2022-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                blank=True, help_text="Select a genre", to="catalog.genre"
            ),
        ),
    ]
