version: '3.7'

services:
  web:
    build:
      context: .
    environment:
      - DOCKER_DEVELOPMENT=development
    command: bash -c "cd booklib && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_booklib:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=booklib
    ports:
      - 5432:5432

volumes:
  postgres_booklib: